//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Fason.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FASON_DIALOG                102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       132
#define IDC_G                           133
#define IDC_X                           1000
#define IDC_Y                           1001
#define IDC_R                           1002
#define IDC_COMBO1                      1005
#define IDC_SEND                        1006
#define IDC_EXIT                        1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
